# Lab 02 CLIENT (M4)
CONFIG_MBOX=y

# LED1 (gpio_exp0)
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_GPIO_PCA95XX=y

# user_button (gpio-keys, Input subsystem)
CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_PRINTK=y
